"""Create initial schema from models

Revision ID: 142d0392172d
Revises: 
Create Date: 2026-03-31 00:07:06.917906
"""
from alembic import op
import sqlalchemy as sa


revision = '142d0392172d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disciplinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_disciplinas_id'), 'disciplinas', ['id'], unique=False)
    op.create_table('linhas_tubulacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_linha', sa.String(length=100), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=True),
    sa.Column('malha', sa.String(length=100), nullable=True),
    sa.Column('sistema', sa.String(length=200), nullable=True),
    sa.Column('sop', sa.String(length=50), nullable=True),
    sa.Column('sub_sop', sa.String(length=50), nullable=True),
    sa.Column('sth', sa.String(length=100), nullable=True),
    sa.Column('pressao_teste', sa.Float(), nullable=True),
    sa.Column('descricao_sistema', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_linhas_numero_linha', 'linhas_tubulacao', ['numero_linha'], unique=False)
    op.create_index('ix_linhas_sth', 'linhas_tubulacao', ['sth'], unique=False)
    op.create_index('ix_linhas_tag', 'linhas_tubulacao', ['tag'], unique=False)
    op.create_index(op.f('ix_linhas_tubulacao_id'), 'linhas_tubulacao', ['id'], unique=False)
    op.create_table('linhas_tubulacao_catalogo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_linha', sa.String(length=150), nullable=False),
    sa.Column('fluido', sa.String(length=50), nullable=True),
    sa.Column('descricao_fluido', sa.Text(), nullable=True),
    sa.Column('pressao_teste', sa.Float(), nullable=True),
    sa.Column('pressao_operacao', sa.Float(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linhas_tubulacao_catalogo_id'), 'linhas_tubulacao_catalogo', ['id'], unique=False)
    op.create_index(op.f('ix_linhas_tubulacao_catalogo_numero_linha'), 'linhas_tubulacao_catalogo', ['numero_linha'], unique=True)
    op.create_table('modelos_relatorio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo', sa.Enum('TESTE_HIDROSTATICO', 'DESCARGA_LINHA', 'FLUSH_LINE', 'TESTE_ESTANQUEIDADE', 'CERTIFICADO_TESTE', name='tipomodelo'), nullable=False),
    sa.Column('arquivo_pdf', sa.String(length=1000), nullable=True),
    sa.Column('caminho_template', sa.String(length=1000), nullable=True),
    sa.Column('campos', sa.JSON(), nullable=True),
    sa.Column('campos_template', sa.JSON(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome', 'tipo', name='uq_modelo_nome_tipo')
    )
    op.create_index(op.f('ix_modelos_relatorio_id'), 'modelos_relatorio', ['id'], unique=False)
    op.create_index('ix_modelos_relatorio_nome', 'modelos_relatorio', ['nome'], unique=False)
    op.create_index('ix_modelos_relatorio_tipo', 'modelos_relatorio', ['tipo'], unique=False)
    op.create_table('sths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=150), nullable=False),
    sa.Column('sop', sa.String(length=50), nullable=True),
    sa.Column('sub_sop', sa.String(length=50), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sths_codigo'), 'sths', ['codigo'], unique=True)
    op.create_index(op.f('ix_sths_id'), 'sths', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMINISTRADOR', 'ENGENHARIA', 'COMISSIONAMENTO', 'CAMPO', 'CQ', name='roleenum'), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('reset_token', sa.String(length=500), nullable=True),
    sa.Column('reset_token_expira', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('documentos_linha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sth_id', sa.Integer(), nullable=False),
    sa.Column('linha_id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sa.Enum('FLUXOGRAMA', 'FLUXOTESTE', 'ISOMETRICO', 'LISTA_SUPORTES', 'MAPA_JUNTAS', name='tipodocumento'), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=500), nullable=True),
    sa.Column('caminho_arquivo', sa.String(length=1000), nullable=True),
    sa.Column('tamanho_bytes', sa.Integer(), nullable=True),
    sa.Column('numero_documento', sa.String(length=200), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_upload', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['linha_id'], ['linhas_tubulacao_catalogo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sth_id'], ['sths.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_doc_linha_linha_id', 'documentos_linha', ['linha_id'], unique=False)
    op.create_index('ix_doc_linha_sth_id', 'documentos_linha', ['sth_id'], unique=False)
    op.create_index('ix_doc_linha_sth_linha_tipo', 'documentos_linha', ['sth_id', 'linha_id', 'tipo_documento'], unique=False)
    op.create_index('ix_doc_linha_tipo', 'documentos_linha', ['tipo_documento'], unique=False)
    op.create_index(op.f('ix_documentos_linha_id'), 'documentos_linha', ['id'], unique=False)
    op.create_table('pastas_teste',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_pasta', sa.String(length=100), nullable=False),
    sa.Column('sth', sa.String(length=100), nullable=True),
    sa.Column('descricao_sistema', sa.Text(), nullable=True),
    sa.Column('pressao_teste', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('CRIADA', 'EM_ANDAMENTO', 'CONCLUIDA', 'CANCELADA', name='statuspasta'), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('criado_por_id', sa.Integer(), nullable=True),
    sa.Column('sth_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['sth_id'], ['sths.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_pasta')
    )
    op.create_index(op.f('ix_pastas_teste_id'), 'pastas_teste', ['id'], unique=False)
    op.create_index('ix_pastas_teste_numero', 'pastas_teste', ['numero_pasta'], unique=False)
    op.create_index('ix_pastas_teste_status', 'pastas_teste', ['status'], unique=False)
    op.create_index('ix_pastas_teste_sth', 'pastas_teste', ['sth'], unique=False)
    op.create_table('spools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sth_id', sa.Integer(), nullable=False),
    sa.Column('linha_id', sa.Integer(), nullable=False),
    sa.Column('codigo_spool', sa.String(length=150), nullable=False),
    sa.Column('origem', sa.String(length=150), nullable=True),
    sa.Column('destino', sa.String(length=150), nullable=True),
    sa.Column('isometrico_ref', sa.String(length=200), nullable=True),
    sa.Column('fluxograma', sa.String(length=500), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['linha_id'], ['linhas_tubulacao_catalogo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sth_id'], ['sths.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sth_id', 'codigo_spool', name='uq_sth_spool')
    )
    op.create_index(op.f('ix_spools_id'), 'spools', ['id'], unique=False)
    op.create_index('ix_spools_linha_id', 'spools', ['linha_id'], unique=False)
    op.create_index('ix_spools_sth_id', 'spools', ['sth_id'], unique=False)
    op.create_table('sth_linhas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sth_id', sa.Integer(), nullable=False),
    sa.Column('linha_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['linha_id'], ['linhas_tubulacao_catalogo.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sth_id'], ['sths.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sth_id', 'linha_id', name='uq_sth_linha')
    )
    op.create_index(op.f('ix_sth_linhas_id'), 'sth_linhas', ['id'], unique=False)
    op.create_table('usuario_disciplinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_disciplinas_id'), 'usuario_disciplinas', ['id'], unique=False)
    op.create_table('documentos_pasta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pasta_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('FLUXOGRAMA', 'FLUXOTESTE', 'ISOMETRICO', 'LISTA_SUPORTES', 'MAPA_JUNTAS', name='tipodocumento'), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=500), nullable=False),
    sa.Column('caminho_arquivo', sa.String(length=1000), nullable=False),
    sa.Column('tamanho_bytes', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pasta_id'], ['pastas_teste.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_pasta_id'), 'documentos_pasta', ['id'], unique=False)
    op.create_index('ix_documentos_pasta_pasta_id', 'documentos_pasta', ['pasta_id'], unique=False)
    op.create_table('pasta_linhas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pasta_id', sa.Integer(), nullable=False),
    sa.Column('linha_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['linha_id'], ['linhas_tubulacao.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pasta_id'], ['pastas_teste.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pasta_id', 'linha_id', name='uq_pasta_linha')
    )
    op.create_index(op.f('ix_pasta_linhas_id'), 'pasta_linhas', ['id'], unique=False)
    op.create_index('ix_pasta_linhas_linha_id', 'pasta_linhas', ['linha_id'], unique=False)
    op.create_index('ix_pasta_linhas_pasta_id', 'pasta_linhas', ['pasta_id'], unique=False)
    op.create_table('pasta_testes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pasta_id', sa.Integer(), nullable=False),
    sa.Column('modelo_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.Column('obrigatorio', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelos_relatorio.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pasta_id'], ['pastas_teste.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pasta_testes_id'), 'pasta_testes', ['id'], unique=False)
    op.create_index('ix_pasta_testes_pasta_id', 'pasta_testes', ['pasta_id'], unique=False)
    op.create_table('relatorios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pasta_id', sa.Integer(), nullable=False),
    sa.Column('modelo_id', sa.Integer(), nullable=False),
    sa.Column('linha_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('dados_linha', sa.JSON(), nullable=True),
    sa.Column('dados_execucao', sa.JSON(), nullable=True),
    sa.Column('pressao_inicial', sa.Float(), nullable=True),
    sa.Column('pressao_final', sa.Float(), nullable=True),
    sa.Column('tempo_teste', sa.Float(), nullable=True),
    sa.Column('resultado', sa.String(length=100), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('RASCUNHO', 'PREENCHIDO', 'SINCRONIZADO', 'APROVADO', 'REJEITADO', name='statusrelatorio'), nullable=True),
    sa.Column('sincronizado', sa.Boolean(), nullable=True),
    sa.Column('sincronizado_em', sa.DateTime(), nullable=True),
    sa.Column('offline_id', sa.String(length=200), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['linha_id'], ['linhas_tubulacao.id'], ),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelos_relatorio.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pasta_id'], ['pastas_teste.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relatorios_id'), 'relatorios', ['id'], unique=False)
    op.create_index('ix_relatorios_pasta_id', 'relatorios', ['pasta_id'], unique=False)
    op.create_table('relatorios_execucao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pasta_id', sa.Integer(), nullable=False),
    sa.Column('linha_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('dados_preenchidos', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PENDENTE', 'EM_EXECUCAO', 'CONCLUIDO', 'REPROVADO', name='statusexecucao'), nullable=False),
    sa.Column('data_execucao', sa.DateTime(), nullable=True),
    sa.Column('usuario_execucao', sa.String(length=200), nullable=True),
    sa.Column('data_sincronizacao', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['linha_id'], ['linhas_tubulacao.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pasta_id'], ['pastas_teste.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['modelos_relatorio.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pasta_id', 'linha_id', 'template_id', name='uq_execucao_pasta_linha_template')
    )
    op.create_index(op.f('ix_relatorios_execucao_id'), 'relatorios_execucao', ['id'], unique=False)
    op.create_index('ix_relatorios_execucao_pasta_id', 'relatorios_execucao', ['pasta_id'], unique=False)
    op.create_index('ix_relatorios_execucao_status', 'relatorios_execucao', ['status'], unique=False)
    op.create_index('ix_relatorios_execucao_template_id', 'relatorios_execucao', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_relatorios_execucao_template_id', table_name='relatorios_execucao')
    op.drop_index('ix_relatorios_execucao_status', table_name='relatorios_execucao')
    op.drop_index('ix_relatorios_execucao_pasta_id', table_name='relatorios_execucao')
    op.drop_index(op.f('ix_relatorios_execucao_id'), table_name='relatorios_execucao')
    op.drop_table('relatorios_execucao')
    op.drop_index('ix_relatorios_pasta_id', table_name='relatorios')
    op.drop_index(op.f('ix_relatorios_id'), table_name='relatorios')
    op.drop_table('relatorios')
    op.drop_index('ix_pasta_testes_pasta_id', table_name='pasta_testes')
    op.drop_index(op.f('ix_pasta_testes_id'), table_name='pasta_testes')
    op.drop_table('pasta_testes')
    op.drop_index('ix_pasta_linhas_pasta_id', table_name='pasta_linhas')
    op.drop_index('ix_pasta_linhas_linha_id', table_name='pasta_linhas')
    op.drop_index(op.f('ix_pasta_linhas_id'), table_name='pasta_linhas')
    op.drop_table('pasta_linhas')
    op.drop_index('ix_documentos_pasta_pasta_id', table_name='documentos_pasta')
    op.drop_index(op.f('ix_documentos_pasta_id'), table_name='documentos_pasta')
    op.drop_table('documentos_pasta')
    op.drop_index(op.f('ix_usuario_disciplinas_id'), table_name='usuario_disciplinas')
    op.drop_table('usuario_disciplinas')
    op.drop_index(op.f('ix_sth_linhas_id'), table_name='sth_linhas')
    op.drop_table('sth_linhas')
    op.drop_index('ix_spools_sth_id', table_name='spools')
    op.drop_index('ix_spools_linha_id', table_name='spools')
    op.drop_index(op.f('ix_spools_id'), table_name='spools')
    op.drop_table('spools')
    op.drop_index('ix_pastas_teste_sth', table_name='pastas_teste')
    op.drop_index('ix_pastas_teste_status', table_name='pastas_teste')
    op.drop_index('ix_pastas_teste_numero', table_name='pastas_teste')
    op.drop_index(op.f('ix_pastas_teste_id'), table_name='pastas_teste')
    op.drop_table('pastas_teste')
    op.drop_index(op.f('ix_documentos_linha_id'), table_name='documentos_linha')
    op.drop_index('ix_doc_linha_tipo', table_name='documentos_linha')
    op.drop_index('ix_doc_linha_sth_linha_tipo', table_name='documentos_linha')
    op.drop_index('ix_doc_linha_sth_id', table_name='documentos_linha')
    op.drop_index('ix_doc_linha_linha_id', table_name='documentos_linha')
    op.drop_table('documentos_linha')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_sths_id'), table_name='sths')
    op.drop_index(op.f('ix_sths_codigo'), table_name='sths')
    op.drop_table('sths')
    op.drop_index('ix_modelos_relatorio_tipo', table_name='modelos_relatorio')
    op.drop_index('ix_modelos_relatorio_nome', table_name='modelos_relatorio')
    op.drop_index(op.f('ix_modelos_relatorio_id'), table_name='modelos_relatorio')
    op.drop_table('modelos_relatorio')
    op.drop_index(op.f('ix_linhas_tubulacao_catalogo_numero_linha'), table_name='linhas_tubulacao_catalogo')
    op.drop_index(op.f('ix_linhas_tubulacao_catalogo_id'), table_name='linhas_tubulacao_catalogo')
    op.drop_table('linhas_tubulacao_catalogo')
    op.drop_index(op.f('ix_linhas_tubulacao_id'), table_name='linhas_tubulacao')
    op.drop_index('ix_linhas_tag', table_name='linhas_tubulacao')
    op.drop_index('ix_linhas_sth', table_name='linhas_tubulacao')
    op.drop_index('ix_linhas_numero_linha', table_name='linhas_tubulacao')
    op.drop_table('linhas_tubulacao')
    op.drop_index(op.f('ix_disciplinas_id'), table_name='disciplinas')
    op.drop_table('disciplinas')
    # ### end Alembic commands ###
